= Asciidoctor Templates Compiler
:source-language: ruby
// custom
:gem-name: asciidoctor-templates-compiler
:gem-version: 0.4.2
:gh-name: jirutka/{gem-name}
:gh-branch: master
:codacy-id: b23b8c6503474ea5b13537eaef0c73d5

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch={gh-branch}[Build Status, link="https://travis-ci.org/{gh-name}"]
image:https://api.codacy.com/project/badge/Coverage/{codacy-id}["Test Coverage", link="https://www.codacy.com/app/{gh-name}"]
image:https://api.codacy.com/project/badge/Grade/{codacy-id}["Codacy Code quality", link="https://www.codacy.com/app/{gh-name}"]
image:https://img.shields.io/gem/v/{gem-name}.svg?style=flat[Gem Version, link="https://rubygems.org/gems/{gem-name}"]
endif::env-github[]

This tool allows to precompile Slim templates into Ruby code and assemble them into a single-file pure Ruby converter (backend).

TODO


== Installation

Add this line to your application’s Gemfile:

[source, subs="+attributes"]
group :development do
  gem '{gem-name}', '~> {gem-version}'
end

or to your gemspec:

[source, subs="+attributes"]
s.add_development_dependency '{gem-name}', '~> {gem-version}'

and then execute:

[source, sh]
$ bundle install


== Usage

The main entry point is method `Asciidoctor::TemplatesCompiler::Slim#compile_converter` (for Slim) that accepts the following keyword arguments.

backend_info::
  A hash of keys for `backend_info`: `basebackend`, `outfilesuffix`, `filetype`, `htmlsyntax`, `supports_templates` (supported since Asciidoctor ≥ 1.5.7).

class_name::
  Full name of the converter class to generate (e.g. `My::HTML::Converter`).
  This argument is **required**.

delegate_backend::
  Name of the backend (converter) to use as a fallback for AST nodes not supported by your converter.
  If not specified (default), no fallback will be used and converter will raise `NoMethodError` when it try to convert an unsupported node.

engine_opts::
  A Hash of options to pass into the templating engine that compiles templates into Ruby code.

output::
  An output stream (`IO` object like opened file, `$stdout`, …) to write the generated converter into.
  Default is `StringIO.new` (it’s the return value of `#compile_converter`).

pretty::
  Enable pretty-formatting of the generated Ruby code (generated by Slim/Temple)?
  Default is `false`.

register_for::
  An array of backend names that the generated converter should be registered in Asciidoctor to handle.
  Default is empty.

templates_dir::
  Path of the directory where to look for templates (`*.slim` files not starting with `_`, in the case of Slim) and (optional) `helpers.rb`.
  This argument is **required**.


=== Examples

[source, subs="+attributes"]
.Minimal example
----
require '{gem-name}'

File.open('converter.rb', 'w') do |file|
  Asciidoctor::TemplatesCompiler::Slim.compile_converter(
      templates_dir: 'data/templates',
      class_name: 'ShinyHtml::Converter',
      delegate_backend: 'html5',
      register_for: ['shiny-html'],
      backend_info: {
        basebackend: 'html',
        outfilesuffix: '.html',
        filetype: 'html',
      },
      pretty: true,
      output: file)
end
----

[source, subs="+attributes"]
.Example of usage in Rakefile
----
#!/usr/bin/env rake

CONVERTER_FILE = 'lib/asciidoctor/shiny_html/converter.rb'
TEMPLATES_DIR = 'data/templates'

namespace :build do

  file CONVERTER_FILE, [:mode] => FileList["#{TEMPLATES_DIR}/*"] do |t, args|
    require '{gem-name}'

    File.open(CONVERTER_FILE, 'w') do |file|
      $stderr.puts "Generating #{file.path}."
      Asciidoctor::TemplatesCompiler::Slim.compile_converter(
          templates_dir: TEMPLATES_DIR,
          class_name: 'Asciidoctor::ShinyHtml::Converter',
          delegate_backend: 'html5',
          register_for: ['shiny-html'],
          backend_info: {
            basebackend: 'html',
            outfilesuffix: '.html',
            filetype: 'html',
          },
          pretty: (args[:mode] == :pretty),
          output: file)
    end
  end

  namespace :converter do
    desc 'Compile Slim templates and generate converter.rb (pretty mode)'
    task :pretty do
      Rake::Task[CONVERTER_FILE].invoke(:pretty)
    end

    desc 'Compile Slim templates and generate converter.rb (fast mode)'
    task :fast do
      Rake::Task[CONVERTER_FILE].invoke
    end
  end

  task :converter => 'converter:pretty'
end

task :build => 'build:converter:pretty'

task :clean do
  rm_rf CONVERTER_FILE
end
----

You can also look into https://github.com/jirutka/asciidoctor-html5s/[asciidoctor-html5s] for a real-world example including integration with https://github.com/asciidoctor/asciidoctor-doctest/[Asciidoctor::DocTest].


== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
